default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: 2003
  host: localhost

development:
  <<: *default
  database: journal_main_development

test:
  <<: *default
  database: journal_main_test

production:
  <<: *default
  database: journal_main_production
  username: your_production_username
  password: <%= ENV['JOURNAL_MAIN_DATABASE_PASSWORD'] %>
