default: &default
  adapter: postgresql
  encoding: unicode
  database: postgres
  pool: 5
  username: postgres
  password: 2003
  host: localhost

development:
  <<: *default
  database: journal_main_development

test:
  <<: *default
  database: journal_main_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
