default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: 2003
  host: localhost

development:
  <<: *default
  database: journal_main_development

test:
  <<: *default
  database: journal_main_test

production:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV['DATABASE_URL'] %>